<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<<<<<<< HEAD
<testsuite hostname="Rithesh" failures="3" tests="9" name="differentapp.LaunchApplication" time="30.911" errors="0" timestamp="2025-07-26T18:34:04 IST" skipped="6">
  <testcase classname="differentapp.LaunchApplication" name="test3" time="3.289">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="test3" time="3.255">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at differentapp.LaunchApplication.test3(LaunchApplication.java:49)
=======
<testsuite hostname="Rithesh" failures="0" tests="4" name="differentapp.LaunchApplication" time="40.783" errors="2" timestamp="2025-07-13T18:19:54 IST" skipped="2">
  <testcase classname="differentapp.LaunchApplication" name="test" time="10.844">
    <error message="Cannot invoke &quot;org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)&quot; because &quot;report.TakeSS.driver&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)" because "report.TakeSS.driver" is null
at report.TakeSS.takess(TakeSS.java:18)
at differentapp.LoginInToApp.loginPage(LoginInToApp.java:23)
at differentapp.LaunchApplication.test(LaunchApplication.java:26)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="test" time="11.615">
    <skipped/>
  </testcase> <!-- test -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="testTwo" time="9.341">
    <skipped/>
  </testcase> <!-- testTwo -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="testTwo" time="8.983">
    <error message="Cannot invoke &quot;org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)&quot; because &quot;report.TakeSS.driver&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.TakesScreenshot.getScreenshotAs(org.openqa.selenium.OutputType)" because "report.TakeSS.driver" is null
at report.TakeSS.takess(TakeSS.java:18)
at differentapp.LoginInToApp.loginPage(LoginInToApp.java:23)
at differentapp.LaunchApplication.testTwo(LaunchApplication.java:34)
>>>>>>> b54eae38f68f498f88da10ba2f21e6be1106df1c
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
<<<<<<< HEAD
    </failure>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="test3" time="5.055">
    <skipped/>
  </testcase> <!-- test3 -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="test4" time="3.262">
    <skipped/>
  </testcase> <!-- test4 -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="test4" time="3.636">
    <skipped/>
  </testcase> <!-- test4 -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="test4" time="3.277">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at differentapp.LaunchApplication.test4(LaunchApplication.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- test4 -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="test5" time="3.322">
    <skipped/>
  </testcase> <!-- test5 -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="test5" time="2.628">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at differentapp.LaunchApplication.test5(LaunchApplication.java:64)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </failure>
  </testcase> <!-- test5 -->
  <system-out/>
  <testcase classname="differentapp.LaunchApplication" name="test5" time="3.187">
    <skipped/>
  </testcase> <!-- test5 -->
=======
    </error>
  </testcase> <!-- testTwo -->
>>>>>>> b54eae38f68f498f88da10ba2f21e6be1106df1c
  <system-out/>
</testsuite> <!-- differentapp.LaunchApplication -->
